"""Validate matrix artifacts and assemble one publishable GitHub Release set."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PROMPT_TEMPLATES = {
    "HapSign-Prompt-ExternalToolchain": (
        PROJECT_ROOT / "prompts" / "HAPSIGN_PROMPT_EXTERNAL_TOOLCHAIN.md"
    ),
    "HapSign-Prompt-Portable": (
        PROJECT_ROOT / "prompts" / "HAPSIGN_PROMPT_PORTABLE.md"
    ),
}

PRODUCT_MATRIX = (
    ("HapSign-GUI", "windows", "x64", ".zip"),
    ("HapSign-CLI-ExternalToolchain", "windows", "x64", ".zip"),
    ("HapSign-CLI-Portable", "windows", "x64", ".zip"),
    ("HapSign-CLI-ExternalToolchain", "linux", "x64", ".tar.gz"),
    ("HapSign-CLI-Portable", "linux", "x64", ".tar.gz"),
    ("HapSign-CLI-ExternalToolchain", "macos", "arm64", ".zip"),
)


def version_from_tag(tag: str) -> str:
    if not re.fullmatch(r"v\d+\.\d+\.\d+(?:-(?:alpha|beta|rc)\.\d+)?", tag):
        raise RuntimeError(f"Unsupported release tag: {tag}")
    return tag[1:]


def expected_product_names(version: str) -> tuple[str, ...]:
    return tuple(
        f"{product}-v{version}-{platform_name}-{architecture}{extension}"
        for product, platform_name, architecture, extension in PRODUCT_MATRIX
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _find_unique(input_dir: Path, filename: str) -> Path:
    matches = [path for path in input_dir.rglob(filename) if path.is_file()]
    if not matches:
        raise RuntimeError(f"Missing release artifact: {filename}")
    if len(matches) > 1:
        raise RuntimeError(f"Duplicate release artifact: {filename}")
    return matches[0]


def _render_prompts(output_dir: Path, *, tag: str, version: str) -> list[Path]:
    rendered: list[Path] = []
    for name, template in PROMPT_TEMPLATES.items():
        content = template.read_text(encoding="utf-8")
        if "__HAPSIGN_RELEASE_TAG__" not in content:
            raise RuntimeError(
                f"Prompt template has no release placeholder: {template}"
            )
        content = content.replace("__HAPSIGN_RELEASE_TAG__", tag)
        target = output_dir / f"{name}-v{version}.md"
        target.write_text(content, encoding="utf-8")
        rendered.append(target)
    return rendered


def assemble_release(
    *,
    tag: str,
    input_dir: Path,
    output_dir: Path,
    source_commit: str | None = None,
) -> list[Path]:
    version = version_from_tag(tag)
    output_dir.mkdir(parents=True, exist_ok=True)
    published: list[Path] = []

    for filename in expected_product_names(version):
        source = _find_unique(input_dir, filename)
        target = output_dir / filename
        shutil.copy2(source, target)
        published.append(target)

    published.extend(_render_prompts(output_dir, tag=tag, version=version))
    assets = []
    for path in sorted(published, key=lambda item: item.name):
        binary = path.suffix != ".md"
        assets.append(
            {
                "name": path.name,
                "size": path.stat().st_size,
                "sha256": sha256(path),
                "code_signed": "-macos-" in path.name if binary else None,
                "publisher_signed": False if binary else None,
                "macos_adhoc_signature": ("-macos-" in path.name if binary else None),
                "notarized": False if binary else None,
            }
        )
    manifest = {
        "schema": 1,
        "release": tag,
        "prerelease": "-" in version,
        "source_commit": source_commit or os.environ.get("GITHUB_SHA", ""),
        "cli_protocol": 2,
        "official_binaries_publisher_signed": False,
        "macos_adhoc_signature": "mandatory for arm64; no publisher identity",
        "notarized": False,
        "code_signing_policy": (
            "No official binary uses a trusted publisher identity. macOS arm64 "
            "contains only the mandatory ad-hoc signature generated by PyInstaller. "
            "Users who require publisher signing must build and sign from source."
        ),
        "support": {
            "windows": {"architectures": ["x64"], "gui": True},
            "linux": {
                "architectures": ["x64"],
                "baseline": "Ubuntu 22.04",
                "other_distributions": "experimental",
            },
            "macos": {"architectures": ["arm64"], "x64": "unsupported"},
        },
        "assets": assets,
    }
    manifest_path = output_dir / "release-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    checksum_paths = sorted([*published, manifest_path], key=lambda item: item.name)
    checksums = output_dir / "SHA256SUMS"
    checksums.write_text(
        "".join(f"{sha256(path)}  {path.name}\n" for path in checksum_paths),
        encoding="ascii",
    )
    return [*published, manifest_path, checksums]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--source-commit")
    args = parser.parse_args()
    try:
        assets = assemble_release(
            tag=args.tag,
            input_dir=args.input_dir.resolve(),
            output_dir=args.output_dir.resolve(),
            source_commit=args.source_commit,
        )
    except RuntimeError as exc:
        print(f"Release assembly failed: {exc}", file=sys.stderr)
        return 1
    for asset in assets:
        print(asset)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
